/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardLayoutImport } from './routes/_dashboard-layout'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardLayoutDashboardIndexImport } from './routes/_dashboard-layout/dashboard/index'
import { Route as DashboardLayoutDashboardVerticalIndexImport } from './routes/_dashboard-layout/dashboard/vertical/index'
import { Route as DashboardLayoutDashboardVentsIndexImport } from './routes/_dashboard-layout/dashboard/vents/index'
import { Route as DashboardLayoutDashboardSightglassesIndexImport } from './routes/_dashboard-layout/dashboard/sightglasses/index'
import { Route as DashboardLayoutDashboardResinsIndexImport } from './routes/_dashboard-layout/dashboard/resins/index'
import { Route as DashboardLayoutDashboardOtherIndexImport } from './routes/_dashboard-layout/dashboard/other/index'
import { Route as DashboardLayoutDashboardNozzlesIndexImport } from './routes/_dashboard-layout/dashboard/nozzles/index'
import { Route as DashboardLayoutDashboardManwaysIndexImport } from './routes/_dashboard-layout/dashboard/manways/index'
import { Route as DashboardLayoutDashboardLiftlugsIndexImport } from './routes/_dashboard-layout/dashboard/liftlugs/index'
import { Route as DashboardLayoutDashboardLedgesIndexImport } from './routes/_dashboard-layout/dashboard/ledges/index'
import { Route as DashboardLayoutDashboardLaminatesIndexImport } from './routes/_dashboard-layout/dashboard/laminates/index'
import { Route as DashboardLayoutDashboardHorizontalIndexImport } from './routes/_dashboard-layout/dashboard/horizontal/index'
import { Route as DashboardLayoutDashboardGlassesIndexImport } from './routes/_dashboard-layout/dashboard/glasses/index'
import { Route as DashboardLayoutDashboardGasketsIndexImport } from './routes/_dashboard-layout/dashboard/gaskets/index'
import { Route as DashboardLayoutDashboardCustomersIndexImport } from './routes/_dashboard-layout/dashboard/customers/index'
import { Route as DashboardLayoutDashboardBoltsIndexImport } from './routes/_dashboard-layout/dashboard/bolts/index'
import { Route as DashboardLayoutDashboardAdditivesIndexImport } from './routes/_dashboard-layout/dashboard/additives/index'
import { Route as DashboardLayoutDashboardVertical6Import } from './routes/_dashboard-layout/dashboard/vertical/6'
import { Route as DashboardLayoutDashboardVertical5Import } from './routes/_dashboard-layout/dashboard/vertical/5'
import { Route as DashboardLayoutDashboardVertical4Import } from './routes/_dashboard-layout/dashboard/vertical/4'
import { Route as DashboardLayoutDashboardVertical3Import } from './routes/_dashboard-layout/dashboard/vertical/3'
import { Route as DashboardLayoutDashboardVertical2Import } from './routes/_dashboard-layout/dashboard/vertical/2'
import { Route as DashboardLayoutDashboardVertical1Import } from './routes/_dashboard-layout/dashboard/vertical/1'
import { Route as DashboardLayoutDashboardSightglassesIdImport } from './routes/_dashboard-layout/dashboard/sightglasses/$id'
import { Route as DashboardLayoutDashboardNozzlesIdImport } from './routes/_dashboard-layout/dashboard/nozzles/$id'
import { Route as DashboardLayoutDashboardManwaysIdImport } from './routes/_dashboard-layout/dashboard/manways/$id'
import { Route as DashboardLayoutDashboardLaminatesIdImport } from './routes/_dashboard-layout/dashboard/laminates/$id'
import { Route as DashboardLayoutDashboardHorizontal7Import } from './routes/_dashboard-layout/dashboard/horizontal/7'
import { Route as DashboardLayoutDashboardHorizontal6Import } from './routes/_dashboard-layout/dashboard/horizontal/6'
import { Route as DashboardLayoutDashboardHorizontal5Import } from './routes/_dashboard-layout/dashboard/horizontal/5'
import { Route as DashboardLayoutDashboardHorizontal4Import } from './routes/_dashboard-layout/dashboard/horizontal/4'
import { Route as DashboardLayoutDashboardHorizontal3Import } from './routes/_dashboard-layout/dashboard/horizontal/3'
import { Route as DashboardLayoutDashboardHorizontal2Import } from './routes/_dashboard-layout/dashboard/horizontal/2'
import { Route as DashboardLayoutDashboardHorizontal1Import } from './routes/_dashboard-layout/dashboard/horizontal/1'
import { Route as DashboardLayoutDashboardGasketsIdImport } from './routes/_dashboard-layout/dashboard/gaskets/$id'
import { Route as DashboardLayoutDashboardCustomersIdImport } from './routes/_dashboard-layout/dashboard/customers/$id'
import { Route as DashboardLayoutDashboardBoltsIdImport } from './routes/_dashboard-layout/dashboard/bolts/$id'

// Create/Update Routes

const DashboardLayoutRoute = DashboardLayoutImport.update({
  id: '/_dashboard-layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardLayoutDashboardIndexRoute =
  DashboardLayoutDashboardIndexImport.update({
    path: '/dashboard/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutDashboardVerticalIndexRoute =
  DashboardLayoutDashboardVerticalIndexImport.update({
    path: '/dashboard/vertical/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutDashboardVentsIndexRoute =
  DashboardLayoutDashboardVentsIndexImport.update({
    path: '/dashboard/vents/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutDashboardSightglassesIndexRoute =
  DashboardLayoutDashboardSightglassesIndexImport.update({
    path: '/dashboard/sightglasses/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutDashboardResinsIndexRoute =
  DashboardLayoutDashboardResinsIndexImport.update({
    path: '/dashboard/resins/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutDashboardOtherIndexRoute =
  DashboardLayoutDashboardOtherIndexImport.update({
    path: '/dashboard/other/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutDashboardNozzlesIndexRoute =
  DashboardLayoutDashboardNozzlesIndexImport.update({
    path: '/dashboard/nozzles/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutDashboardManwaysIndexRoute =
  DashboardLayoutDashboardManwaysIndexImport.update({
    path: '/dashboard/manways/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutDashboardLiftlugsIndexRoute =
  DashboardLayoutDashboardLiftlugsIndexImport.update({
    path: '/dashboard/liftlugs/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutDashboardLedgesIndexRoute =
  DashboardLayoutDashboardLedgesIndexImport.update({
    path: '/dashboard/ledges/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutDashboardLaminatesIndexRoute =
  DashboardLayoutDashboardLaminatesIndexImport.update({
    path: '/dashboard/laminates/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutDashboardHorizontalIndexRoute =
  DashboardLayoutDashboardHorizontalIndexImport.update({
    path: '/dashboard/horizontal/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutDashboardGlassesIndexRoute =
  DashboardLayoutDashboardGlassesIndexImport.update({
    path: '/dashboard/glasses/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutDashboardGasketsIndexRoute =
  DashboardLayoutDashboardGasketsIndexImport.update({
    path: '/dashboard/gaskets/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutDashboardCustomersIndexRoute =
  DashboardLayoutDashboardCustomersIndexImport.update({
    path: '/dashboard/customers/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutDashboardBoltsIndexRoute =
  DashboardLayoutDashboardBoltsIndexImport.update({
    path: '/dashboard/bolts/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutDashboardAdditivesIndexRoute =
  DashboardLayoutDashboardAdditivesIndexImport.update({
    path: '/dashboard/additives/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutDashboardVertical6Route =
  DashboardLayoutDashboardVertical6Import.update({
    path: '/dashboard/vertical/6',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutDashboardVertical5Route =
  DashboardLayoutDashboardVertical5Import.update({
    path: '/dashboard/vertical/5',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutDashboardVertical4Route =
  DashboardLayoutDashboardVertical4Import.update({
    path: '/dashboard/vertical/4',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutDashboardVertical3Route =
  DashboardLayoutDashboardVertical3Import.update({
    path: '/dashboard/vertical/3',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutDashboardVertical2Route =
  DashboardLayoutDashboardVertical2Import.update({
    path: '/dashboard/vertical/2',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutDashboardVertical1Route =
  DashboardLayoutDashboardVertical1Import.update({
    path: '/dashboard/vertical/1',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutDashboardSightglassesIdRoute =
  DashboardLayoutDashboardSightglassesIdImport.update({
    path: '/dashboard/sightglasses/$id',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutDashboardNozzlesIdRoute =
  DashboardLayoutDashboardNozzlesIdImport.update({
    path: '/dashboard/nozzles/$id',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutDashboardManwaysIdRoute =
  DashboardLayoutDashboardManwaysIdImport.update({
    path: '/dashboard/manways/$id',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutDashboardLaminatesIdRoute =
  DashboardLayoutDashboardLaminatesIdImport.update({
    path: '/dashboard/laminates/$id',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutDashboardHorizontal7Route =
  DashboardLayoutDashboardHorizontal7Import.update({
    path: '/dashboard/horizontal/7',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutDashboardHorizontal6Route =
  DashboardLayoutDashboardHorizontal6Import.update({
    path: '/dashboard/horizontal/6',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutDashboardHorizontal5Route =
  DashboardLayoutDashboardHorizontal5Import.update({
    path: '/dashboard/horizontal/5',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutDashboardHorizontal4Route =
  DashboardLayoutDashboardHorizontal4Import.update({
    path: '/dashboard/horizontal/4',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutDashboardHorizontal3Route =
  DashboardLayoutDashboardHorizontal3Import.update({
    path: '/dashboard/horizontal/3',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutDashboardHorizontal2Route =
  DashboardLayoutDashboardHorizontal2Import.update({
    path: '/dashboard/horizontal/2',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutDashboardHorizontal1Route =
  DashboardLayoutDashboardHorizontal1Import.update({
    path: '/dashboard/horizontal/1',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutDashboardGasketsIdRoute =
  DashboardLayoutDashboardGasketsIdImport.update({
    path: '/dashboard/gaskets/$id',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutDashboardCustomersIdRoute =
  DashboardLayoutDashboardCustomersIdImport.update({
    path: '/dashboard/customers/$id',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutDashboardBoltsIdRoute =
  DashboardLayoutDashboardBoltsIdImport.update({
    path: '/dashboard/bolts/$id',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_dashboard-layout': {
      preLoaderRoute: typeof DashboardLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_dashboard-layout/dashboard/': {
      preLoaderRoute: typeof DashboardLayoutDashboardIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboard-layout/dashboard/bolts/$id': {
      preLoaderRoute: typeof DashboardLayoutDashboardBoltsIdImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboard-layout/dashboard/customers/$id': {
      preLoaderRoute: typeof DashboardLayoutDashboardCustomersIdImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboard-layout/dashboard/gaskets/$id': {
      preLoaderRoute: typeof DashboardLayoutDashboardGasketsIdImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboard-layout/dashboard/horizontal/1': {
      preLoaderRoute: typeof DashboardLayoutDashboardHorizontal1Import
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboard-layout/dashboard/horizontal/2': {
      preLoaderRoute: typeof DashboardLayoutDashboardHorizontal2Import
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboard-layout/dashboard/horizontal/3': {
      preLoaderRoute: typeof DashboardLayoutDashboardHorizontal3Import
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboard-layout/dashboard/horizontal/4': {
      preLoaderRoute: typeof DashboardLayoutDashboardHorizontal4Import
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboard-layout/dashboard/horizontal/5': {
      preLoaderRoute: typeof DashboardLayoutDashboardHorizontal5Import
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboard-layout/dashboard/horizontal/6': {
      preLoaderRoute: typeof DashboardLayoutDashboardHorizontal6Import
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboard-layout/dashboard/horizontal/7': {
      preLoaderRoute: typeof DashboardLayoutDashboardHorizontal7Import
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboard-layout/dashboard/laminates/$id': {
      preLoaderRoute: typeof DashboardLayoutDashboardLaminatesIdImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboard-layout/dashboard/manways/$id': {
      preLoaderRoute: typeof DashboardLayoutDashboardManwaysIdImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboard-layout/dashboard/nozzles/$id': {
      preLoaderRoute: typeof DashboardLayoutDashboardNozzlesIdImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboard-layout/dashboard/sightglasses/$id': {
      preLoaderRoute: typeof DashboardLayoutDashboardSightglassesIdImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboard-layout/dashboard/vertical/1': {
      preLoaderRoute: typeof DashboardLayoutDashboardVertical1Import
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboard-layout/dashboard/vertical/2': {
      preLoaderRoute: typeof DashboardLayoutDashboardVertical2Import
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboard-layout/dashboard/vertical/3': {
      preLoaderRoute: typeof DashboardLayoutDashboardVertical3Import
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboard-layout/dashboard/vertical/4': {
      preLoaderRoute: typeof DashboardLayoutDashboardVertical4Import
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboard-layout/dashboard/vertical/5': {
      preLoaderRoute: typeof DashboardLayoutDashboardVertical5Import
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboard-layout/dashboard/vertical/6': {
      preLoaderRoute: typeof DashboardLayoutDashboardVertical6Import
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboard-layout/dashboard/additives/': {
      preLoaderRoute: typeof DashboardLayoutDashboardAdditivesIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboard-layout/dashboard/bolts/': {
      preLoaderRoute: typeof DashboardLayoutDashboardBoltsIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboard-layout/dashboard/customers/': {
      preLoaderRoute: typeof DashboardLayoutDashboardCustomersIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboard-layout/dashboard/gaskets/': {
      preLoaderRoute: typeof DashboardLayoutDashboardGasketsIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboard-layout/dashboard/glasses/': {
      preLoaderRoute: typeof DashboardLayoutDashboardGlassesIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboard-layout/dashboard/horizontal/': {
      preLoaderRoute: typeof DashboardLayoutDashboardHorizontalIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboard-layout/dashboard/laminates/': {
      preLoaderRoute: typeof DashboardLayoutDashboardLaminatesIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboard-layout/dashboard/ledges/': {
      preLoaderRoute: typeof DashboardLayoutDashboardLedgesIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboard-layout/dashboard/liftlugs/': {
      preLoaderRoute: typeof DashboardLayoutDashboardLiftlugsIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboard-layout/dashboard/manways/': {
      preLoaderRoute: typeof DashboardLayoutDashboardManwaysIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboard-layout/dashboard/nozzles/': {
      preLoaderRoute: typeof DashboardLayoutDashboardNozzlesIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboard-layout/dashboard/other/': {
      preLoaderRoute: typeof DashboardLayoutDashboardOtherIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboard-layout/dashboard/resins/': {
      preLoaderRoute: typeof DashboardLayoutDashboardResinsIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboard-layout/dashboard/sightglasses/': {
      preLoaderRoute: typeof DashboardLayoutDashboardSightglassesIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboard-layout/dashboard/vents/': {
      preLoaderRoute: typeof DashboardLayoutDashboardVentsIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboard-layout/dashboard/vertical/': {
      preLoaderRoute: typeof DashboardLayoutDashboardVerticalIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  DashboardLayoutRoute.addChildren([
    DashboardLayoutDashboardIndexRoute,
    DashboardLayoutDashboardBoltsIdRoute,
    DashboardLayoutDashboardCustomersIdRoute,
    DashboardLayoutDashboardGasketsIdRoute,
    DashboardLayoutDashboardHorizontal1Route,
    DashboardLayoutDashboardHorizontal2Route,
    DashboardLayoutDashboardHorizontal3Route,
    DashboardLayoutDashboardHorizontal4Route,
    DashboardLayoutDashboardHorizontal5Route,
    DashboardLayoutDashboardHorizontal6Route,
    DashboardLayoutDashboardHorizontal7Route,
    DashboardLayoutDashboardLaminatesIdRoute,
    DashboardLayoutDashboardManwaysIdRoute,
    DashboardLayoutDashboardNozzlesIdRoute,
    DashboardLayoutDashboardSightglassesIdRoute,
    DashboardLayoutDashboardVertical1Route,
    DashboardLayoutDashboardVertical2Route,
    DashboardLayoutDashboardVertical3Route,
    DashboardLayoutDashboardVertical4Route,
    DashboardLayoutDashboardVertical5Route,
    DashboardLayoutDashboardVertical6Route,
    DashboardLayoutDashboardAdditivesIndexRoute,
    DashboardLayoutDashboardBoltsIndexRoute,
    DashboardLayoutDashboardCustomersIndexRoute,
    DashboardLayoutDashboardGasketsIndexRoute,
    DashboardLayoutDashboardGlassesIndexRoute,
    DashboardLayoutDashboardHorizontalIndexRoute,
    DashboardLayoutDashboardLaminatesIndexRoute,
    DashboardLayoutDashboardLedgesIndexRoute,
    DashboardLayoutDashboardLiftlugsIndexRoute,
    DashboardLayoutDashboardManwaysIndexRoute,
    DashboardLayoutDashboardNozzlesIndexRoute,
    DashboardLayoutDashboardOtherIndexRoute,
    DashboardLayoutDashboardResinsIndexRoute,
    DashboardLayoutDashboardSightglassesIndexRoute,
    DashboardLayoutDashboardVentsIndexRoute,
    DashboardLayoutDashboardVerticalIndexRoute,
  ]),
])

/* prettier-ignore-end */
